# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'ui/scraper_ui.ui'
#
# Created by: PyQt5 UI code generator 5.15.11
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(1509, 786)
        MainWindow.setStyleSheet("/* Основное окно и вкладки */\n"
"QMainWindow {\n"
"    background-color: #f4f7f6;\n"
"    color: #222831;\n"
"    font-family: \'Segoe UI\', sans-serif;\n"
"}\n"
"\n"
"QTabWidget::pane {\n"
"    border: none;\n"
"    background-color: #ffffff;\n"
"}\n"
"\n"
"QTabBar::tab {\n"
"    background-color: #ffffff;\n"
"    color: #222831;\n"
"    padding: 8px 15px;\n"
"    border: 1px solid #dddddd;\n"
"    border-radius: 6px;\n"
"    margin-right: 4px;\n"
"}\n"
"\n"
"QTabBar::tab:selected {\n"
"    background-color: #00adb5;\n"
"    color: #ffffff;\n"
"    border: none;\n"
"}\n"
"\n"
"/* Кнопки */\n"
"QPushButton {\n"
"    background-color: #00adb5;\n"
"    color: white;\n"
"    padding: 6px 15px;\n"
"    border-radius: 6px;\n"
"}\n"
"\n"
"QPushButton:hover {\n"
"    background-color: #028a91;\n"
"}\n"
"\n"
"/* Поля ввода */\n"
"QLineEdit, QTextEdit {\n"
"    background-color: #ffffff;\n"
"    color: #222831;\n"
"    border: 1px solid #dddddd;\n"
"    border-radius: 5px;\n"
"    padding: 4px;\n"
"}\n"
"\n"
"/* Таблица и списки */\n"
"QTableWidget, QListWidget {\n"
"    background-color: #ffffff;\n"
"    color: #222831;\n"
"    gridline-color: #f0f0f0;\n"
"    border: 1px solid #dddddd;\n"
"    border-radius: 6px;\n"
"}\n"
"\n"
"/* Логи */\n"
"QTextBrowser {\n"
"    background-color: #ffffff;\n"
"    color: #222831;\n"
"    border: 1px solid #dddddd;\n"
"    border-radius: 6px;\n"
"}\n"
"\n"
"/* ===== ДОПОЛНЕНИЯ ===== */\n"
"\n"
"/* Label (подписи и текст) */\n"
"QLabel {\n"
"    color: #393e46;\n"
"    font-size: 14px;\n"
"}\n"
"\n"
"/* CheckBox */\n"
"QCheckBox {\n"
"    color: #222831;\n"
"    padding: 3px;\n"
"    spacing: 5px;\n"
"}\n"
"\n"
"QCheckBox::indicator {\n"
"    width: 16px;\n"
"    height: 16px;\n"
"    border-radius: 3px;\n"
"    border: 1px solid #00adb5;\n"
"    background-color: #ffffff;\n"
"}\n"
"\n"
"QCheckBox::indicator:checked {\n"
"    background-color: #00adb5;\n"
"    border: none;\n"
"}\n"
"\n"
"/* ComboBox */\n"
"QComboBox {\n"
"    background-color: #ffffff;\n"
"    color: #222831;\n"
"    border: 1px solid #dddddd;\n"
"    border-radius: 5px;\n"
"    padding: 4px;\n"
"}\n"
"\n"
"QComboBox::drop-down {\n"
"    border: none;\n"
"}\n"
"\n"
"QComboBox QAbstractItemView {\n"
"    background-color: #ffffff;\n"
"    selection-background-color: #00adb5;\n"
"    selection-color: #ffffff;\n"
"    border-radius: 5px;\n"
"    padding: 3px;\n"
"}\n"
"\n"
"QToolBar::separator {\n"
"    background-color: #333333;  /* Тёмно-серый / почти чёрный */\n"
"    width: 2px;\n"
"    margin: 4px;\n"
"}\n"
"")
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.tabWidget = QtWidgets.QTabWidget(self.centralwidget)
        self.tabWidget.setEnabled(True)
        self.tabWidget.setGeometry(QtCore.QRect(0, 0, 1331, 741))
        self.tabWidget.setObjectName("tabWidget")
        self.tab = QtWidgets.QWidget()
        self.tab.setObjectName("tab")
        self.tasks_table = QtWidgets.QTableWidget(self.tab)
        self.tasks_table.setGeometry(QtCore.QRect(0, 0, 1331, 701))
        self.tasks_table.setObjectName("tasks_table")
        self.tasks_table.setColumnCount(11)
        self.tasks_table.setRowCount(0)
        item = QtWidgets.QTableWidgetItem()
        self.tasks_table.setHorizontalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        self.tasks_table.setHorizontalHeaderItem(1, item)
        item = QtWidgets.QTableWidgetItem()
        self.tasks_table.setHorizontalHeaderItem(2, item)
        item = QtWidgets.QTableWidgetItem()
        self.tasks_table.setHorizontalHeaderItem(3, item)
        item = QtWidgets.QTableWidgetItem()
        self.tasks_table.setHorizontalHeaderItem(4, item)
        item = QtWidgets.QTableWidgetItem()
        self.tasks_table.setHorizontalHeaderItem(5, item)
        item = QtWidgets.QTableWidgetItem()
        self.tasks_table.setHorizontalHeaderItem(6, item)
        item = QtWidgets.QTableWidgetItem()
        self.tasks_table.setHorizontalHeaderItem(7, item)
        item = QtWidgets.QTableWidgetItem()
        self.tasks_table.setHorizontalHeaderItem(8, item)
        item = QtWidgets.QTableWidgetItem()
        self.tasks_table.setHorizontalHeaderItem(9, item)
        item = QtWidgets.QTableWidgetItem()
        self.tasks_table.setHorizontalHeaderItem(10, item)
        self.tabWidget.addTab(self.tab, "")
        self.tab_2 = QtWidgets.QWidget()
        self.tab_2.setObjectName("tab_2")
        self.label_4 = QtWidgets.QLabel(self.tab_2)
        self.label_4.setGeometry(QtCore.QRect(0, 0, 131, 16))
        self.label_4.setObjectName("label_4")
        self.export_button = QtWidgets.QPushButton(self.tab_2)
        self.export_button.setGeometry(QtCore.QRect(0, 50, 231, 31))
        self.export_button.setObjectName("export_button")
        self.format_combobox = QtWidgets.QComboBox(self.tab_2)
        self.format_combobox.setGeometry(QtCore.QRect(0, 20, 231, 23))
        self.format_combobox.setObjectName("format_combobox")
        self.format_combobox.addItem("")
        self.format_combobox.addItem("")
        self.format_combobox.addItem("")
        self.format_combobox.addItem("")
        self.format_combobox.addItem("")
        self.format_combobox.addItem("")
        self.parse_data_table = QtWidgets.QTableWidget(self.tab_2)
        self.parse_data_table.setGeometry(QtCore.QRect(0, 150, 1231, 571))
        self.parse_data_table.setObjectName("parse_data_table")
        self.parse_data_table.setColumnCount(0)
        self.parse_data_table.setRowCount(0)
        self.Data_button = QtWidgets.QPushButton(self.tab_2)
        self.Data_button.setGeometry(QtCore.QRect(240, 50, 231, 31))
        self.Data_button.setObjectName("Data_button")
        self.browse_button = QtWidgets.QPushButton(self.tab_2)
        self.browse_button.setGeometry(QtCore.QRect(240, 20, 231, 23))
        self.browse_button.setObjectName("browse_button")
        self.label_6 = QtWidgets.QLabel(self.tab_2)
        self.label_6.setGeometry(QtCore.QRect(0, 130, 161, 16))
        font = QtGui.QFont()
        font.setPointSize(-1)
        font.setBold(True)
        font.setWeight(75)
        self.label_6.setFont(font)
        self.label_6.setObjectName("label_6")
        self.tabWidget.addTab(self.tab_2, "")
        self.tab_3 = QtWidgets.QWidget()
        self.tab_3.setObjectName("tab_3")
        self.checkBox = QtWidgets.QCheckBox(self.tab_3)
        self.checkBox.setGeometry(QtCore.QRect(0, 0, 111, 21))
        self.checkBox.setObjectName("checkBox")
        self.checkBox_2 = QtWidgets.QCheckBox(self.tab_3)
        self.checkBox_2.setGeometry(QtCore.QRect(0, 30, 181, 21))
        self.checkBox_2.setObjectName("checkBox_2")
        self.checkBox_3 = QtWidgets.QCheckBox(self.tab_3)
        self.checkBox_3.setGeometry(QtCore.QRect(0, 60, 141, 21))
        self.checkBox_3.setObjectName("checkBox_3")
        self.proxy_input = QtWidgets.QLineEdit(self.tab_3)
        self.proxy_input.setGeometry(QtCore.QRect(180, 30, 231, 23))
        self.proxy_input.setObjectName("proxy_input")
        self.label_3 = QtWidgets.QLabel(self.tab_3)
        self.label_3.setGeometry(QtCore.QRect(180, 10, 171, 20))
        font = QtGui.QFont()
        font.setPointSize(-1)
        font.setBold(True)
        font.setWeight(75)
        self.label_3.setFont(font)
        self.label_3.setObjectName("label_3")
        self.check_proxy_button = QtWidgets.QPushButton(self.tab_3)
        self.check_proxy_button.setGeometry(QtCore.QRect(180, 60, 231, 31))
        self.check_proxy_button.setObjectName("check_proxy_button")
        self.safe_button = QtWidgets.QPushButton(self.tab_3)
        self.safe_button.setGeometry(QtCore.QRect(0, 90, 131, 23))
        self.safe_button.setObjectName("safe_button")
        self.reset_button = QtWidgets.QPushButton(self.tab_3)
        self.reset_button.setGeometry(QtCore.QRect(0, 120, 131, 23))
        self.reset_button.setObjectName("reset_button")
        self.tabWidget.addTab(self.tab_3, "")
        self.lcd_total = QtWidgets.QLCDNumber(self.centralwidget)
        self.lcd_total.setGeometry(QtCore.QRect(1330, 30, 64, 23))
        self.lcd_total.setObjectName("lcd_total")
        self.lcd_running = QtWidgets.QLCDNumber(self.centralwidget)
        self.lcd_running.setGeometry(QtCore.QRect(1330, 90, 64, 23))
        self.lcd_running.setObjectName("lcd_running")
        self.lcd_success = QtWidgets.QLCDNumber(self.centralwidget)
        self.lcd_success.setGeometry(QtCore.QRect(1330, 150, 64, 23))
        self.lcd_success.setObjectName("lcd_success")
        self.lcd_error = QtWidgets.QLCDNumber(self.centralwidget)
        self.lcd_error.setGeometry(QtCore.QRect(1330, 210, 64, 23))
        self.lcd_error.setObjectName("lcd_error")
        self.lcd_stopped = QtWidgets.QLCDNumber(self.centralwidget)
        self.lcd_stopped.setGeometry(QtCore.QRect(1330, 270, 64, 23))
        self.lcd_stopped.setObjectName("lcd_stopped")
        self.label_Task = QtWidgets.QLabel(self.centralwidget)
        self.label_Task.setGeometry(QtCore.QRect(1400, 30, 81, 21))
        self.label_Task.setObjectName("label_Task")
        self.label_Process = QtWidgets.QLabel(self.centralwidget)
        self.label_Process.setGeometry(QtCore.QRect(1400, 90, 81, 21))
        self.label_Process.setObjectName("label_Process")
        self.label_Sucessfull = QtWidgets.QLabel(self.centralwidget)
        self.label_Sucessfull.setGeometry(QtCore.QRect(1400, 150, 81, 21))
        self.label_Sucessfull.setObjectName("label_Sucessfull")
        self.label_Error = QtWidgets.QLabel(self.centralwidget)
        self.label_Error.setGeometry(QtCore.QRect(1400, 210, 81, 21))
        self.label_Error.setObjectName("label_Error")
        self.label_Stoped = QtWidgets.QLabel(self.centralwidget)
        self.label_Stoped.setGeometry(QtCore.QRect(1400, 270, 81, 21))
        self.label_Stoped.setObjectName("label_Stoped")
        MainWindow.setCentralWidget(self.centralwidget)
        self.toolBar = QtWidgets.QToolBar(MainWindow)
        self.toolBar.setObjectName("toolBar")
        MainWindow.addToolBar(QtCore.Qt.TopToolBarArea, self.toolBar)
        self.statusBar = QtWidgets.QStatusBar(MainWindow)
        self.statusBar.setObjectName("statusBar")
        MainWindow.setStatusBar(self.statusBar)
        self.action_add_task_2 = QtWidgets.QAction(MainWindow)
        self.action_add_task_2.setObjectName("action_add_task_2")
        self.action_del_task = QtWidgets.QAction(MainWindow)
        self.action_del_task.setObjectName("action_del_task")
        self.action_run_task = QtWidgets.QAction(MainWindow)
        self.action_run_task.setObjectName("action_run_task")
        self.action_manage_sessions = QtWidgets.QAction(MainWindow)
        self.action_manage_sessions.setObjectName("action_manage_sessions")
        self.action_save_session = QtWidgets.QAction(MainWindow)
        self.action_save_session.setObjectName("action_save_session")
        self.action_search_tasks = QtWidgets.QAction(MainWindow)
        self.action_search_tasks.setObjectName("action_search_tasks")
        self.action_run_selected_bulk = QtWidgets.QAction(MainWindow)
        self.action_run_selected_bulk.setObjectName("action_run_selected_bulk")
        self.action_delete_selected_bulk = QtWidgets.QAction(MainWindow)
        self.action_delete_selected_bulk.setObjectName("action_delete_selected_bulk")
        self.action_save_selected_bulk = QtWidgets.QAction(MainWindow)
        self.action_save_selected_bulk.setObjectName("action_save_selected_bulk")
        self.action_run_analytics = QtWidgets.QAction(MainWindow)
        self.action_run_analytics.setObjectName("action_run_analytics")
        self.action_open_calendar = QtWidgets.QAction(MainWindow)
        self.action_open_calendar.setObjectName("action_open_calendar")
        self.toolBar.addAction(self.action_add_task_2)
        self.toolBar.addAction(self.action_del_task)
        self.toolBar.addAction(self.action_delete_selected_bulk)
        self.toolBar.addSeparator()
        self.toolBar.addAction(self.action_run_task)
        self.toolBar.addAction(self.action_run_selected_bulk)
        self.toolBar.addSeparator()
        self.toolBar.addAction(self.action_save_selected_bulk)
        self.toolBar.addAction(self.action_save_session)
        self.toolBar.addSeparator()
        self.toolBar.addAction(self.action_manage_sessions)
        self.toolBar.addAction(self.action_search_tasks)
        self.toolBar.addSeparator()
        self.toolBar.addAction(self.action_run_analytics)
        self.toolBar.addAction(self.action_open_calendar)
        self.toolBar.addSeparator()

        self.retranslateUi(MainWindow)
        self.tabWidget.setCurrentIndex(0)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        item = self.tasks_table.horizontalHeaderItem(0)
        item.setText(_translate("MainWindow", "№"))
        item = self.tasks_table.horizontalHeaderItem(1)
        item.setText(_translate("MainWindow", "URL"))
        item = self.tasks_table.horizontalHeaderItem(2)
        item.setText(_translate("MainWindow", "Selectors"))
        item = self.tasks_table.horizontalHeaderItem(3)
        item.setText(_translate("MainWindow", "Methode"))
        item = self.tasks_table.horizontalHeaderItem(4)
        item.setText(_translate("MainWindow", "Status"))
        item = self.tasks_table.horizontalHeaderItem(5)
        item.setText(_translate("MainWindow", "Action"))
        item = self.tasks_table.horizontalHeaderItem(6)
        item.setText(_translate("MainWindow", "Save"))
        item = self.tasks_table.horizontalHeaderItem(7)
        item.setText(_translate("MainWindow", "Cookies"))
        item = self.tasks_table.horizontalHeaderItem(8)
        item.setText(_translate("MainWindow", "Params"))
        item = self.tasks_table.horizontalHeaderItem(9)
        item.setText(_translate("MainWindow", "Timer"))
        item = self.tasks_table.horizontalHeaderItem(10)
        item.setText(_translate("MainWindow", "Last Run"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab), _translate("MainWindow", "Tasks"))
        self.label_4.setText(_translate("MainWindow", "Save parsed data"))
        self.export_button.setText(_translate("MainWindow", "Export"))
        self.format_combobox.setItemText(0, _translate("MainWindow", "default"))
        self.format_combobox.setItemText(1, _translate("MainWindow", "group_by_tags"))
        self.format_combobox.setItemText(2, _translate("MainWindow", "articles"))
        self.format_combobox.setItemText(3, _translate("MainWindow", "with_links"))
        self.format_combobox.setItemText(4, _translate("MainWindow", "CSV"))
        self.format_combobox.setItemText(5, _translate("MainWindow", "Excel"))
        self.Data_button.setText(_translate("MainWindow", "Data Preview"))
        self.browse_button.setText(_translate("MainWindow", "Browse (QFileDialog)"))
        self.label_6.setText(_translate("MainWindow", "Table Data Preview"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_2), _translate("MainWindow", "Export"))
        self.checkBox.setText(_translate("MainWindow", "Dark Theme"))
        self.checkBox_2.setText(_translate("MainWindow", "Auto-saved after parsing"))
        self.checkBox_3.setText(_translate("MainWindow", "Use proxy rotation"))
        self.label_3.setText(_translate("MainWindow", "Type proxy(optional)"))
        self.check_proxy_button.setText(_translate("MainWindow", "Check proxy"))
        self.safe_button.setText(_translate("MainWindow", "Safe settings"))
        self.reset_button.setText(_translate("MainWindow", "Reset to default"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_3), _translate("MainWindow", "Settings"))
        self.label_Task.setText(_translate("MainWindow", "All Tasks"))
        self.label_Process.setText(_translate("MainWindow", "In Process"))
        self.label_Sucessfull.setText(_translate("MainWindow", "Sucessfull"))
        self.label_Error.setText(_translate("MainWindow", "ERROR"))
        self.label_Stoped.setText(_translate("MainWindow", "Stoped"))
        self.toolBar.setWindowTitle(_translate("MainWindow", "toolBar"))
        self.action_add_task_2.setText(_translate("MainWindow", "+ Add Task"))
        self.action_add_task_2.setToolTip(_translate("MainWindow", "Add Task"))
        self.action_del_task.setText(_translate("MainWindow", "🗑 Delete\n"
""))
        self.action_run_task.setText(_translate("MainWindow", "▶ Run Task\n"
""))
        self.action_manage_sessions.setText(_translate("MainWindow", "📁 Session"))
        self.action_save_session.setText(_translate("MainWindow", "💾 Save Session"))
        self.action_search_tasks.setText(_translate("MainWindow", "🔍 Search"))
        self.action_run_selected_bulk.setText(_translate("MainWindow", "▶ Run Selected"))
        self.action_delete_selected_bulk.setText(_translate("MainWindow", "🗑 Delete Selected"))
        self.action_save_selected_bulk.setText(_translate("MainWindow", "💾 Save Selected"))
        self.action_run_analytics.setText(_translate("MainWindow", "📊 Create Graphics"))
        self.action_open_calendar.setText(_translate("MainWindow", "📆 Calendar"))
